modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="memesproject"
version="0.1.5(0.1b5)"
displayName="MemesProject-Forge"
credits="TexTrue,TexTrueStudio"
displayURL="https://github.com/TexTrueStudio/MemesProject-Forge"
logoFile="logo.png"
authors="TexTrueStudio"

[[dependencies.memesproject]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.memesproject]]
    modId="catalogue"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.memesproject]]
    modId="memesprojectdiscforge"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.memesproject]]
    modId="memesproject_redisc"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"